# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dustin Kreidler
email: dkreidler@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Well, I was hoping this would be my cool github pages page... but it looks
  like I already did some gitHub training with Jekyll... and now I need to 
  figure out what's where. Awesome. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dkreidler.github.io" # the base hostname & protocol for your site
twitter_username: dkreidler
github_username:  dkreidler

# Build settings
markdown: kramdown
